name: Continuous integration
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run golangci-lit
        uses: docker://golangci/golangci-lint:latest-alpine
        with:
          args: golangci-lint run ./...
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Build app
        run: make build
      - name: Show app version
        run: ./realworld --version
